# Generated by Django 2.1.3 on 2018-11-09 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('introduction', models.TextField(verbose_name='引言')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.CategoriesModel', verbose_name='分类')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.TagModel', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
    ]
