# Generated by Django 2.1.3 on 2018-11-19 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181119_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynumber',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
