# Generated by Django 2.1.3 on 2018-11-22 16:52

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogmodel_visit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='正文'),
        ),
    ]
